repositories:
  - name: minio
    url: https://charts.min.io/ 

releases:
  - name: minio
    namespace: minio
    createNamespace: true
    chart: minio/minio
    values:
      - values-minio.yaml
    set:
      - name: rootUser
        value: admin
      - name: rootPassword
        value: super-secret
